<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ModeloValidador.Abstracciones">
      <HintPath>..\..\SmartHome\ModeloValidador.Abstracciones.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
