// <auto-generated />
using System;
using DataAccess.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SmartHomeDBContext))]
    [Migration("20241003042230_AddCompanyOwnerRoleSeedData")]
    partial class AddCompanyOwnerRoleSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessLogic.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logotype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Rut");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BusinessLogic.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("BusinessLogic.HomeDevices.HomeDevice", b =>
                {
                    b.Property<Guid>("HardwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ConnectionState")
                        .HasColumnType("bit");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HardwareId");

                    b.ToTable("HomeDevices");
                });

            modelBuilder.Entity("BusinessLogic.Homes.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxAmountOfMembers")
                        .HasColumnType("int");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("BusinessLogic.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeOfEvent")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TriggeringDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TriggeringEvent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserItIsAddressedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasRead")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("TriggeringDeviceId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BusinessLogic.Users.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6321a816-3080-1002-aab7-5032779c3714"),
                            Name = "create-administrator"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-1003-aab7-5032779c3714"),
                            Name = "create-companyowner"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-1004-aab7-5032779c3714"),
                            Name = "list-users"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-1005-aab7-5032779c3714"),
                            Name = "list-companies"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-2002-aab7-5032779c3714"),
                            Name = "create-company"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-2003-aab7-5032779c3714"),
                            Name = "create-camera"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-2004-aab7-5032779c3714"),
                            Name = "create-sensor"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6321a816-3080-1001-aab7-5032779c3714"),
                            RoleName = "administrator"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-2001-aab7-5032779c3714"),
                            RoleName = "company-owner"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("administrator");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-1001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-1001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-1001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1005-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-1001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-2002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-2001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-2003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-2001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-2004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-2001-aab7-5032779c3714")
                        });
                });

            modelBuilder.Entity("BusinessLogic.CompanyOwners.CompanyOwner", b =>
                {
                    b.HasBaseType("BusinessLogic.Users.User");

                    b.Property<bool>("AccountState")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AssociatedCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("AssociatedCompanyId");

                    b.HasDiscriminator().HasValue("companyowner");
                });

            modelBuilder.Entity("BusinessLogic.HomeOwners.HomeOwner", b =>
                {
                    b.HasBaseType("BusinessLogic.Users.User");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("homeowner");
                });

            modelBuilder.Entity("BusinessLogic.Devices.Device", b =>
                {
                    b.HasOne("BusinessLogic.Companies.Company", "CompanyItIsAssociatedTo")
                        .WithMany("AssociatedDevices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyItIsAssociatedTo");
                });

            modelBuilder.Entity("BusinessLogic.Homes.Home", b =>
                {
                    b.OwnsOne("BusinessLogic.Homes.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("HomeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DoorNumber")
                                .HasColumnType("int");

                            b1.Property<string>("MainStreet")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HomeId");

                            b1.ToTable("Homes");

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.OwnsOne("BusinessLogic.Homes.GeographicLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("HomeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Latitude")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Longitude")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HomeId");

                            b1.ToTable("Homes");

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.Notifications.Notification", b =>
                {
                    b.HasOne("BusinessLogic.Homes.Home", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.HomeDevices.HomeDevice", "TriggeringDevice")
                        .WithMany()
                        .HasForeignKey("TriggeringDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("TriggeringDevice");
                });

            modelBuilder.Entity("BusinessLogic.Users.User", b =>
                {
                    b.HasOne("BusinessLogic.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("BusinessLogic.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.CompanyOwners.CompanyOwner", b =>
                {
                    b.HasOne("BusinessLogic.Companies.Company", "AssociatedCompany")
                        .WithMany()
                        .HasForeignKey("AssociatedCompanyId");

                    b.Navigation("AssociatedCompany");
                });

            modelBuilder.Entity("BusinessLogic.Companies.Company", b =>
                {
                    b.Navigation("AssociatedDevices");
                });

            modelBuilder.Entity("BusinessLogic.Users.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
