// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using DataAccess.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SmartHomeDBContext))]
    partial class SmartHomeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceModelValidatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logotype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Rut");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfDevice")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Devices");

                    b.HasDiscriminator<string>("TypeOfDevice").HasValue("sensor");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HomeOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxAmountOfMembers")
                        .HasColumnType("int");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeOwnerId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("Domain.HomeDevice", b =>
                {
                    b.Property<Guid>("HardwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConnectionState")
                        .HasColumnType("bit");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomItIsInId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HardwareId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HomeId");

                    b.HasIndex("RoomItIsInId");

                    b.ToTable("HomeDevices");
                });

            modelBuilder.Entity("Domain.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociatedHomeOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedHomeOwnerId");

                    b.HasIndex("HomeId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeOfEvent")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TriggeringDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TriggeringEvent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserItIsAddressedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasRead")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("TriggeringDeviceId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6321a816-3080-1002-aab7-5032779c3714"),
                            Name = "create-administrator"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-1003-aab7-5032779c3714"),
                            Name = "create-companyowner"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-1004-aab7-5032779c3714"),
                            Name = "list-users"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-1005-aab7-5032779c3714"),
                            Name = "list-companies"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-2002-aab7-5032779c3714"),
                            Name = "create-company"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-2003-aab7-5032779c3714"),
                            Name = "create-camera"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-2004-aab7-5032779c3714"),
                            Name = "create-sensor"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-3002-aab7-5032779c3714"),
                            Name = "create-home"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-3003-aab7-5032779c3714"),
                            Name = "add-member-to-home"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-3004-aab7-5032779c3714"),
                            Name = "add-device-to-home"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-3005-aab7-5032779c3714"),
                            Name = "list-members-of-home"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-3006-aab7-5032779c3714"),
                            Name = "list-devices-of-home"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-3007-aab7-5032779c3714"),
                            Name = "add-permissions-to-member"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-4002-aab7-5032779c3714"),
                            Name = "add-device-to-specific-home"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-4003-aab7-5032779c3714"),
                            Name = "list-devices-of-specific-home"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-4004-aab7-5032779c3714"),
                            Name = "receive-notifications"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-4005-aab7-5032779c3714"),
                            Name = "change-alias-of-specific-device"
                        });
                });

            modelBuilder.Entity("Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6321a816-3080-1001-aab7-5032779c3714"),
                            RoleName = "administrator"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-2001-aab7-5032779c3714"),
                            RoleName = "company-owner"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-3001-aab7-5032779c3714"),
                            RoleName = "home-owner"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-4001-aab7-5032779c3714"),
                            RoleName = "home-specific-permissions"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-5001-aab7-5032779c3714"),
                            RoleName = "admin-home-owner"
                        },
                        new
                        {
                            Id = new Guid("6321a816-3080-5002-aab7-5032779c3714"),
                            RoleName = "company-owner-home-owner"
                        });
                });

            modelBuilder.Entity("Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeItBelongsToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeItBelongsToId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("administrator");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-6618-4bab-a6b6-9a32a11893f8"),
                            CreationDate = new DateTime(2024, 10, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "administrator@gmail.com",
                            Name = "User",
                            Password = "admin123!",
                            RoleId = new Guid("6321a816-3080-1001-aab7-5032779c3714"),
                            Surname = "Admin"
                        });
                });

            modelBuilder.Entity("MemberPermission", b =>
                {
                    b.Property<Guid>("MembersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MembersId", "PermissionsId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("MemberPermissions", (string)null);
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-1001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-1001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-1001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1005-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-1001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-2002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-2001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-2003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-2001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-2004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-2001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-3001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-3001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-3001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3005-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-3001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3006-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-3001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3007-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-3001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-4002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-4001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-4003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-4001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-4004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-4001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-4005-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-4001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-1005-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3005-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3006-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3007-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5001-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-2002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5002-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-2003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5002-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-2004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5002-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3002-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5002-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3003-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5002-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3004-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5002-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3005-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5002-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3006-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5002-aab7-5032779c3714")
                        },
                        new
                        {
                            PermissionId = new Guid("6321a816-3080-3007-aab7-5032779c3714"),
                            RoleId = new Guid("6321a816-3080-5002-aab7-5032779c3714")
                        });
                });

            modelBuilder.Entity("Domain.Camera", b =>
                {
                    b.HasBaseType("Domain.Device");

                    b.Property<bool>("CanBeUsedIndoors")
                        .HasColumnType("bit");

                    b.Property<bool>("CanBeUsedOutdoors")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMovementDetectionSupport")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPersonDetectionSupport")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("camera");
                });

            modelBuilder.Entity("Domain.SmartLamp", b =>
                {
                    b.HasBaseType("Domain.Device");

                    b.Property<bool>("IsTurnedOn")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("smartlamp");
                });

            modelBuilder.Entity("Domain.CompanyOwner", b =>
                {
                    b.HasBaseType("Domain.User");

                    b.Property<bool>("AccountState")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AssociatedCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("AssociatedCompanyId")
                        .IsUnique()
                        .HasFilter("[AssociatedCompanyId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("companyowner");
                });

            modelBuilder.Entity("Domain.HomeOwner", b =>
                {
                    b.HasBaseType("Domain.User");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("homeowner");
                });

            modelBuilder.Entity("Domain.Device", b =>
                {
                    b.HasOne("Domain.Company", "CompanyItIsAssociatedTo")
                        .WithMany("AssociatedDevices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyItIsAssociatedTo");
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.HasOne("Domain.User", "HomeOwner")
                        .WithMany()
                        .HasForeignKey("HomeOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("HomeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DoorNumber")
                                .HasColumnType("int");

                            b1.Property<string>("MainStreet")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HomeId");

                            b1.ToTable("Homes");

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.OwnsOne("Domain.GeographicLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("HomeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Latitude")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Longitude")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HomeId");

                            b1.ToTable("Homes");

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("HomeOwner");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.HomeDevice", b =>
                {
                    b.HasOne("Domain.Device", "Device")
                        .WithMany("HomeDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Home", null)
                        .WithMany("AssociatedDevices")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Room", "RoomItIsIn")
                        .WithMany("HomeDevices")
                        .HasForeignKey("RoomItIsInId");

                    b.Navigation("Device");

                    b.Navigation("RoomItIsIn");
                });

            modelBuilder.Entity("Domain.Member", b =>
                {
                    b.HasOne("Domain.User", "AssociatedHomeOwner")
                        .WithMany("Members")
                        .HasForeignKey("AssociatedHomeOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Home", null)
                        .WithMany("Members")
                        .HasForeignKey("HomeId");

                    b.Navigation("AssociatedHomeOwner");
                });

            modelBuilder.Entity("Domain.Notification", b =>
                {
                    b.HasOne("Domain.Home", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.HomeDevice", "TriggeringDevice")
                        .WithMany()
                        .HasForeignKey("TriggeringDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("TriggeringDevice");
                });

            modelBuilder.Entity("Domain.Room", b =>
                {
                    b.HasOne("Domain.Home", "HomeItBelongsTo")
                        .WithMany("Rooms")
                        .HasForeignKey("HomeItBelongsToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeItBelongsTo");
                });

            modelBuilder.Entity("Domain.Session", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithOne("Session")
                        .HasForeignKey("Domain.Session", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.HasOne("Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MemberPermission", b =>
                {
                    b.HasOne("Domain.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CompanyOwner", b =>
                {
                    b.HasOne("Domain.Company", "AssociatedCompany")
                        .WithOne("CompanyOwner")
                        .HasForeignKey("Domain.CompanyOwner", "AssociatedCompanyId");

                    b.Navigation("AssociatedCompany");
                });

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Navigation("AssociatedDevices");

                    b.Navigation("CompanyOwner");
                });

            modelBuilder.Entity("Domain.Device", b =>
                {
                    b.Navigation("HomeDevices");
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Navigation("AssociatedDevices");

                    b.Navigation("Members");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Room", b =>
                {
                    b.Navigation("HomeDevices");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Session");
                });
#pragma warning restore 612, 618
        }
    }
    [ExcludeFromCodeCoverage]
    partial class SmartHomeDBContextModelSnapshot : ModelSnapshot
    {
    }
}
