<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\DTOs\DTOs.csproj" />
    <ProjectReference Include="..\IBusinessLogic\IBusinessLogic.csproj" />
    <ProjectReference Include="..\IDataAccess\IDataAccess.csproj" />
    <ProjectReference Include="..\IImporterService\ImporterService.csproj" />
    <ProjectReference Include="..\NotificationStrategies\NotificationStrategies.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ModeloValidador.Abstracciones">
      <HintPath>..\..\ModeloValidador.Abstracciones.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
